name: ReVanced Experimental Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: "17"
          distribution: "temurin"
          check-latest: true

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Build APKs, force patches on untested YouTube versions
        run: ./build_revanced.sh experimental

      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-experimental"
          draft: false
          prerelease: true
          title: "Experimental ${{ env.date_now }}"
          files: |
            build/*.apk
            vanced-microG.apk
