name: ReVanced Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: "17"
          distribution: "temurin"
          check-latest: true

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Test Build APKs
        run: |
          ./build_revanced.sh
          for filename in build/*.apk; do
            if [ -e "$filename" ]; then
              printf '"%s" exists\n' "$filename"
            else
              echo "APK build failed"
              exit 1
            fi
          done
          rm -rf build
      - name: Test Build Experimental APKS
        run: |
          ./build_revanced.sh experimental
          for filename in build/*.apk; do
            if [ -e "$filename" ]; then
              printf '"%s" exists\n' "$filename"
            else
              echo "APK build failed"
              exit 1
            fi
          done
          rm -rf build
